"""Media_MediaLog_AIWorkerState_added_with_env

Revision ID: 0021224c34cc
Revises: d7ccb29133e6
Create Date: 2026-02-19 16:05:01.731322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0021224c34cc'
down_revision: Union[str, Sequence[str], None] = 'd7ccb29133e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_worker_states',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('tasks_processed_today', sa.Integer(), nullable=False),
    sa.Column('last_reset_date', sa.Date(), nullable=False),
    sa.Column('last_ping', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('media',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('uploader_id', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'UPLOADED', 'EXTRACTING', 'PROCESSING', 'READY', 'FAILED', name='mediastatus'), nullable=False),
    sa.Column('hf_path', sa.String(), nullable=True),
    sa.Column('initial_metadata', sa.JSON(), nullable=True),
    sa.Column('technical_metadata', sa.JSON(), nullable=True),
    sa.Column('assigned_worker', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_worker'], ['ai_worker_states.name'], ),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('media')
    op.drop_table('ai_worker_states')
    # ### end Alembic commands ###
