"""add cascade delete to media_task_logs

Revision ID: 1d620a02b451
Revises: 9b645704d75e
Create Date: 2026-02-23 15:15:37.211245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d620a02b451'
down_revision: Union[str, Sequence[str], None] = '9b645704d75e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('media_task_logs_media_id_fkey'), 'media_task_logs', type_='foreignkey')
    op.create_foreign_key(None, 'media_task_logs', 'media', ['media_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'media_task_logs', type_='foreignkey')
    op.create_foreign_key(op.f('media_task_logs_media_id_fkey'), 'media_task_logs', 'media', ['media_id'], ['id'])
    # ### end Alembic commands ###
