"""added geolocation data fields for media

Revision ID: 1efdd065b3ad
Revises: 1d620a02b451
Create Date: 2026-02-25 15:56:09.142420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1efdd065b3ad'
down_revision: Union[str, Sequence[str], None] = '1d620a02b451'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('media', sa.Column('lng', sa.Float(), nullable=True))
    op.add_column('media', sa.Column('altitude', sa.Float(), nullable=True))
    op.add_column('media', sa.Column('address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'address')
    op.drop_column('media', 'altitude')
    op.drop_column('media', 'lng')
    op.drop_column('media', 'lat')
    # ### end Alembic commands ###
