"""add language column to users

Revision ID: 29f6865b8498
Revises: dba4842be217
Create Date: 2026-02-14 15:29:54.978946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29f6865b8498'
down_revision: Union[str, Sequence[str], None] = 'dba4842be217'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # 1. Add the column allowing NULLs temporarily
    op.add_column("users", sa.Column("language", sa.String(), nullable=True))

    # 2. Fill existing rows with your default value ('en')
    op.execute("UPDATE users SET language = 'en'")

    # 3. Now that no rows are NULL, set the column to NOT NULL
    op.alter_column("users", "language", nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'language')
    # ### end Alembic commands ###
