"""update videodetection model alt->altitude

Revision ID: 41d9ef6e5070
Revises: 74be1bdde5e3
Create Date: 2026-03-28 12:47:22.962326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41d9ef6e5070'
down_revision: Union[str, Sequence[str], None] = '74be1bdde5e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_detections', sa.Column('altitude', sa.Float(), nullable=False, server_default='0'))
    op.drop_column('video_detections', 'alt')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_detections', sa.Column('alt', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False))
    op.drop_column('video_detections', 'altitude')
    # ### end Alembic commands ###
