"""add videodetection model

Revision ID: 4a4cef3d7003
Revises: ffd730336fee
Create Date: 2026-03-17 22:41:23.239068

"""
from typing import Sequence, Union


from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '4a4cef3d7003'
down_revision: Union[str, Sequence[str], None] = 'ffd730336fee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_detections',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('media_id', sa.Uuid(), nullable=False),
        sa.Column('lat', sa.Float(), nullable=False),
        sa.Column('lng', sa.Float(), nullable=False),
        sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
        sa.Column('label', sa.String(), nullable=False),
        sa.Column('confidence', sa.Float(), nullable=False),
        sa.Column('bbox', sa.JSON(), nullable=False),
        sa.Column('timestamp_in_video', sa.Float(), nullable=False),
        sa.Column('frame_hf_path', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_video_loc_gist', 'video_detections', ['location'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_video_loc_gist', table_name='video_detections', postgresql_using='gist')
    op.drop_table('video_detections')
    # ### end Alembic commands ###
