"""update videodetection model

Revision ID: 74be1bdde5e3
Revises: 4a4cef3d7003
Create Date: 2026-03-28 12:42:29.387343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74be1bdde5e3'
down_revision: Union[str, Sequence[str], None] = '4a4cef3d7003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_detections', sa.Column('alt', sa.Float(), nullable=False, server_default='0'))
    op.add_column('video_detections', sa.Column('address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_detections', 'address')
    op.drop_column('video_detections', 'alt')
    # ### end Alembic commands ###
