"""add_failed_reason_and_duplicate_tracking

Revision ID: 7613ab41afc7
Revises: a3b4c5d6e7f8
Create Date: 2026-03-01 14:18:31.621872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7613ab41afc7'
down_revision: Union[str, Sequence[str], None] = 'a3b4c5d6e7f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('original_media_id', sa.Uuid(), nullable=True))
    op.create_foreign_key('fk_media_original_media_id', 'media', 'media', ['original_media_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_media_original_media_id', 'media', type_='foreignkey')
    op.drop_column('media', 'original_media_id')
    # ### end Alembic commands ###
