"""update videodetection model

Revision ID: cd752aeaca2b
Revises: 41d9ef6e5070
Create Date: 2026-03-29 17:18:37.182772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd752aeaca2b'
down_revision: Union[str, Sequence[str], None] = '41d9ef6e5070'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_detections', sa.Column('is_manual', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('video_detections', sa.Column('area_sqm', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_detections', 'area_sqm')
    op.drop_column('video_detections', 'is_manual')
    # ### end Alembic commands ###
