"""add detections to env

Revision ID: d74a13b1e4aa
Revises: c9670d02de70
Create Date: 2026-03-01 11:33:46.181402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd74a13b1e4aa'
down_revision: Union[str, Sequence[str], None] = 'c9670d02de70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('media_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('bbox', sa.JSON(), nullable=False),
    sa.Column('is_manual', sa.Boolean(), nullable=False),
    sa.Column('area_sqm', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detections')
    # ### end Alembic commands ###
