"""Media_MediaLog_AIWorkerState_added

Revision ID: d7ccb29133e6
Revises: 18285c9dd2aa
Create Date: 2026-02-19 16:02:30.755583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7ccb29133e6'
down_revision: Union[str, Sequence[str], None] = '18285c9dd2aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
