"""add type field to media table

Revision ID: ffd730336fee
Revises: 7613ab41afc7
Create Date: 2026-03-15 21:24:40.798978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffd730336fee'
down_revision: Union[str, Sequence[str], None] = '7613ab41afc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create ENUM type explicitly
    mediatype = sa.Enum('IMAGE', 'VIDEO', name='mediatype')
    mediatype.create(op.get_bind(), checkfirst=True)
    op.add_column('media', sa.Column('media_type', mediatype, nullable=False, server_default='IMAGE'))
    op.create_index('idx_media_location', 'media', ['location'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_media_location', table_name='media', postgresql_using='gist')
    op.drop_column('media', 'media_type')
    # Drop ENUM type
    mediatype = sa.Enum('IMAGE', 'VIDEO', name='mediatype')
    mediatype.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
